[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Zhenya <zenjaprihan@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tenacity = "^8.0.1"
uvicorn = "^0.18.3"
fastapi = "^0.82.0"
SQLAlchemy = "^1.4.40"
psycopg2-binary = "^2.9.3"
alembic = "^1.8.1"
pre-commit = "^2.20.0"
httpx = "^0.23.0"
pytz = "^2022.6"
pydantic = {extras = ["email"], version = "^1.10.2"}
celery = "^5.2.7"
flower = "^1.2.0"
redis = {extras = ["hiredis"], version = "^5.0.0"}
sqladmin = "^0.10.0"
gunicorn = "^20.1.0"
itsdangerous = "^2.1.2"
nltk = "^3.8.1"
scikit-learn = "^1.3.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
flake8 = "^5.0.4"
autopep8 = "^1.7.0"
requests = "^2.28.1"
pytest-httpx = "^0.21.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
